### Starting the silos 2018 dataset

In [1]:
import pandas as pd
import os 
import numpy as np
from sklearn.model_selection import train_test_split
import numpy as np

In [23]:
data = pd.read_parquet('../datasets/cic-ids2018dataset/datasets/Botnet-Friday-02-03-2018_TrafficForML_CICFlowMeter.parquet')
data.head(5)

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,6,141385,9,7,553,3773.0,202,0,61.444443,87.534439,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,6,281,2,1,38,0.0,38,0,19.000000,26.870058,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
2,6,279824,11,15,1086,10527.0,385,0,98.727272,129.392502,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
3,6,132,2,0,0,0.0,0,0,0.000000,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4,6,274016,9,13,1285,6141.0,517,0,142.777771,183.887726,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

In [3]:
### Combining all the datasets 
silo_path = '../datasets/cic-ids2018dataset/datasets/'
datasets = []

for filename in os.listdir(silo_path):
    if filename.endswith('.parquet'):
        filepath = os.path.join(silo_path, filename) ### Creating a file path for each directory
        data = pd.read_parquet(filepath)
        datasets.append(data)
    
combined_datasets = pd.concat(datasets, ignore_index=True)
combined_datasets.head(5)
print(combined_datasets.shape[0])

6659532

In [4]:
print(combined_datasets['Label'].value_counts())

Label
Benign                      5329008
DDoS attacks-LOIC-HTTP       575364
DDOS attack-HOIC             198861
DoS attacks-Hulk             145199
Bot                          144535
Infilteration                118483
SSH-Bruteforce                94048
DoS attacks-GoldenEye         41406
DoS attacks-Slowloris          9908
DDOS attack-LOIC-UDP           1730
Brute Force -Web                568
Brute Force -XSS                229
SQL Injection                    85
DoS attacks-SlowHTTPTest         55
FTP-BruteForce                   53
Name: count, dtype: int64

In [5]:
## Only the attack samples 
attack_data = combined_datasets[combined_datasets['Label'] != 'Benign']
benign_data = combined_datasets[combined_datasets['Label'] == 'Benign']

In [6]:
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)
NUM_CLIENTS = 4
ALPHA = 0.5
client_indices = [[] for _ in range(NUM_CLIENTS)]
for label in attack_data['Label'].unique():    
    indices = attack_data[attack_data['Label'] == label].index.to_numpy().copy() ## This returns the row number of each attack type sample
    np.random.shuffle(indices)
    proportions = np.random.dirichlet([ALPHA] * NUM_CLIENTS)
    split_points = (np.cumsum(proportions)[:-1] * len(indices)).astype(int)
    splits = np.split(indices, split_points)
    for client_id in range(NUM_CLIENTS):
        client_indices[client_id].extend(splits[client_id])

### each silo has sttack indices

In [7]:
client_datasets = []
for client_id in range(NUM_CLIENTS):
    attack_count = len(client_indices[client_id])
    benign_sample = benign_data.sample(n = attack_count, random_state=RANDOM_SEED)
    client_dataset = pd.concat(
    [
        attack_data.loc[client_indices[client_id]],
        benign_sample
    ])
    client_datasets.append(client_dataset)

In [8]:
for each in client_datasets:
    print(each.shape)

(1336088, 78)
(290252, 78)
(648204, 78)
(386504, 78)

In [9]:
def binary_silos_converter(df):
    df = df.copy()
    df['Label_Binary'] = df['Label'].apply(lambda x: 0 if x == 'Benign' else 1)
    df = df.drop(columns = 'Label')
    return df

In [10]:
pd1 = client_datasets[0]
pd1_binary = binary_silos_converter(pd1)
print(pd1_binary['Label_Binary'].value_counts())
pd1_binary.to_csv('../silos_datasets/silos_datasets2018/SiloBinaryOne.csv')

Label_Binary
1    668044
0    668044
Name: count, dtype: int64

In [11]:
pd2 = client_datasets[2]
pd2_binary = binary_silos_converter(pd2)
print(pd2_binary['Label_Binary'].value_counts())
pd2_binary.to_csv('../silos_datasets/silos_datasets2018/SiloBinaryTwo.csv')

Label_Binary
1    324102
0    324102
Name: count, dtype: int64

In [12]:
pd3 = client_datasets[3]
pd3_binary = binary_silos_converter(pd3)
print(pd3_binary['Label_Binary'].value_counts())
pd3_binary.to_csv('../silos_datasets/silos_datasets2018/SiloBinaryThree.csv')

Label_Binary
1    193252
0    193252
Name: count, dtype: int64

In [13]:
pd4 = client_datasets[1]
pd4_binary = binary_silos_converter(pd4)
print(pd4_binary['Label_Binary'].value_counts())
pd4_binary.to_csv('../silos_datasets/silos_datasets2018/SiloBinaryFour.csv')

Label_Binary
1    145126
0    145126
Name: count, dtype: int64

In [14]:
### Binary combined datasets
binary_combined_dataset = pd.concat([pd1_binary, pd2_binary, pd3_binary, pd4_binary], ignore_index = True)
binary_combined_dataset.to_csv('../silos_datasets/silos_datasets2018/combined_dataset.csv')

In [15]:
### Creating the train test split for each silos

from sklearn.model_selection import train_test_split ## Imported the train test split library
from sklearn.preprocessing import StandardScaler
def train_validation_test(data, silo_name, random_state = RANDOM_SEED):
    scaler = StandardScaler()
    X = data.drop(columns=['Label_Binary'])
    y = data['Label_Binary']
    silo_path = '../silos_datasets/silos_datasets2018/'
    sending_path = '../FederatedAvg/cicids2018clientdata/nids/'
    X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3,random_state=random_state, stratify = y)
    X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size = 0.5, random_state=random_state, stratify=y_temp)

    X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns)
    X_val_scaled = pd.DataFrame(scaler.transform(X_val), columns=X_val.columns)
    X_test_scaled = pd.DataFrame(scaler.transform(X_test), columns=X_test.columns)
    X_train_scaled.to_csv(f'{sending_path}{silo_name}_X_train.csv', index=False)
    y_train.to_csv(f'{sending_path}{silo_name}_y_train.csv', index=False)
    X_test_scaled.to_csv(f'{sending_path}{silo_name}_X_test.csv', index=False)
    y_test.to_csv(f'{sending_path}{silo_name}_y_test.csv', index=False)
    X_val_scaled.to_csv(f'{sending_path}{silo_name}_X_val.csv', index=False)
    y_val.to_csv(f'{sending_path}{silo_name}_y_val.csv', index=False)

    return X_train_scaled, y_train, X_test_scaled, y_test, X_val_scaled, y_val

In [16]:
train_validation_test(pd1_binary,'siloOne')
train_validation_test(pd2_binary,'siloTwo')
train_validation_test(pd3_binary,'siloThree')
train_validation_test(pd4_binary,'siloFour')

(        Protocol  Flow Duration  Total Fwd Packets  Total Backward Packets  \
 0      -0.368391      -0.204839          -0.046341               -0.009583
 1      -0.368391       2.663041          -0.046687               -0.029912
 2      -0.368391      -0.381740          -0.046687               -0.029912
 3      -0.368391      -0.381766          -0.046687               -0.029912
 4      -0.368391      -0.378811          -0.046514               -0.029912
 ...          ...            ...                ...                     ...
 203171 -0.368391      -0.379758          -0.046687               -0.029912
 203172  2.527328      -0.381791          -0.046860               -0.024829
 203173 -0.368391      -0.381409          -0.046514               -0.009583
 203174 -0.368391      -0.380461          -0.046687               -0.029912
 203175 -0.368391      -0.222301          -0.046168               -0.014665

         Fwd Packets Length Total  Bwd Packets Length Total  \
 0                      -0.045746                 -0.010765
 1                      -0.048285                 -0.014162
 2                      -0.048285                 -0.014162
 3                      -0.048285                 -0.014162
 4                      -0.048285                 -0.014162
 ...                          ...                       ...
 203171                 -0.048285                 -0.014162
 203172                 -0.048091                 -0.013980
 203173                 -0.046531                 -0.013711
 203174                 -0.048285                 -0.014162
 203175                 -0.043255                 -0.012739

         Fwd Packet Length Max  Fwd Packet Length Min  Fwd Packet Length Mean  \
 0                    0.674760              -0.283289                0.761976
 1                   -0.829974              -0.283289               -1.027630
 2                   -0.829974              -0.283289               -1.027630
 3                   -0.829974              -0.283289               -1.027630
 4                   -0.829974              -0.283289               -1.027630
 ...                       ...                    ...                     ...
 203171              -0.829974              -0.283289               -1.027630
 203172              -0.715206               1.454291               -0.481648
 203173               0.209313              -0.283289                0.620425
 203174              -0.829974              -0.283289               -1.027630
 203175               2.150801              -0.283289                1.808440

         Fwd Packet Length Std  ...  Fwd Act Data Packets  Fwd Seg Size Min  \
 0                    0.952168  ...             -0.046258          1.327418
 1                   -0.886296  ...             -0.046431         -0.204643
 2                   -0.886296  ...             -0.046431         -0.204643
 3                   -0.886296  ...             -0.046431          1.327418
 4                   -0.886296  ...             -0.046431          1.327418
 ...                       ...  ...                   ...               ...
 203171              -0.886296  ...             -0.046431          1.327418
 203172              -0.886296  ...             -0.046431         -1.736704
 203173               0.579927  ...             -0.046258         -0.204643
 203174              -0.886296  ...             -0.046431          1.327418
 203175               2.371094  ...             -0.046258          1.327418

         Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  \
 0         -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 1         -0.067283   -0.050933   -0.077534   -0.057422   5.046538 -0.084961
 2         -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 3         -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 4         -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 ...             ...         ...         ...         ...        ...       ...
 203171    -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 203172    -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 203173    -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 203174    -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 203175    -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961

         Idle Max  Idle Min
 0      -0.295088 -0.285410
 1       4.952291  5.086457
 2      -0.295088 -0.285410
 3      -0.295088 -0.285410
 4      -0.295088 -0.285410
 ...          ...       ...
 203171 -0.295088 -0.285410
 203172 -0.295088 -0.285410
 203173 -0.295088 -0.285410
 203174 -0.295088 -0.285410
 203175 -0.295088 -0.285410

 [203176 rows x 77 columns],
 4542850    1
 3436035    0
 5427151    0
 3949478    1
 4462564    1
           ..
 4494200    1
 5127922    0
 1935487    1
 4250711    1
 4392275    0
 Name: Label_Binary, Length: 203176, dtype: int64,
        Protocol  Flow Duration  Total Fwd Packets  Total Backward Packets  \
 0     -0.368391       3.735519          -0.044610                0.041239
 1     -0.368391      -0.379345          -0.046514               -0.029912
 2     -0.368391      -0.381415          -0.046514               -0.009583
 3     -0.368391      -0.165800          -0.046341               -0.009583
 4      2.527328      -0.380502          -0.046687               -0.019747
 ...         ...            ...                ...                     ...
 43533 -0.368391      -0.380939          -0.046687               -0.029912
 43534 -0.368391      -0.381416          -0.046514               -0.009583
 43535 -0.368391      -0.381813          -0.046860               -0.024829
 43536 -0.368391       2.669203          -0.046687               -0.029912
 43537 -0.368391      -0.381210          -0.046687                0.031075

        Fwd Packets Length Total  Bwd Packets Length Total  \
 0                     -0.043734                  0.013332
 1                     -0.048285                 -0.014162
 2                     -0.046531                 -0.013711
 3                     -0.047763                 -0.013354
 4                     -0.047854                 -0.013323
 ...                         ...                       ...
 43533                 -0.048285                 -0.014162
 43534                 -0.046531                 -0.013711
 43535                 -0.048285                 -0.014162
 43536                 -0.048285                 -0.014162
 43537                 -0.048285                 -0.013711

        Fwd Packet Length Max  Fwd Packet Length Min  Fwd Packet Length Mean  \
 0                  -0.039351              -0.283289               -0.111161
 1                  -0.829974              -0.283289               -1.027630
 2                   0.209313              -0.283289                0.620425
 3                  -0.520738              -0.283289               -0.659851
 4                  -0.702454               1.647355               -0.420984
 ...                      ...                    ...                     ...
 43533              -0.829974              -0.283289               -1.027630
 43534               0.209313              -0.283289                0.620425
 43535              -0.829974              -0.283289               -1.027630
 43536              -0.829974              -0.283289               -1.027630
 43537              -0.829974              -0.283289               -1.027630

        Fwd Packet Length Std  ...  Fwd Act Data Packets  Fwd Seg Size Min  \
 0                  -0.219520  ...             -0.045219         -0.204643
 1                  -0.886296  ...             -0.046431          1.327418
 2                   0.579927  ...             -0.046258         -0.204643
 3                  -0.508476  ...             -0.046258         -0.204643
 4                  -0.886296  ...             -0.046258         -1.736704
 ...                      ...  ...                   ...               ...
 43533              -0.886296  ...             -0.046431          1.327418
 43534               0.579927  ...             -0.046258         -0.204643
 43535              -0.886296  ...             -0.046431         -0.204643
 43536              -0.886296  ...             -0.046431         -0.204643
 43537              -0.886296  ...             -0.046431         -0.204643

        Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  \
 0         0.071728    0.174283    0.097160   -0.002072   3.305767  0.002385
 1        -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 2        -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 3        -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 4        -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 ...            ...         ...         ...         ...        ...       ...
 43533    -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 43534    -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 43535    -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 43536    -0.067283   -0.050933   -0.077534   -0.057422   5.057341 -0.084961
 43537    -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961

        Idle Max  Idle Min
 0      3.247163  3.328425
 1     -0.295088 -0.285410
 2     -0.295088 -0.285410
 3     -0.295088 -0.285410
 4     -0.295088 -0.285410
 ...         ...       ...
 43533 -0.295088 -0.285410
 43534 -0.295088 -0.285410
 43535 -0.295088 -0.285410
 43536  4.962910  5.097328
 43537 -0.295088 -0.285410

 [43538 rows x 77 columns],
 1720598    0
 4267735    1
 1831552    1
 3451449    0
 580093     0
           ..
 4401008    1
 1962056    1
 3298029    0
 3939288    0
 1851487    1
 Name: Label_Binary, Length: 43538, dtype: int64,
        Protocol  Flow Duration  Total Fwd Packets  Total Backward Packets  \
 0     -0.368391      -0.381100          -0.046687               -0.029912
 1     -0.368391      -0.198083          -0.046168               -0.009583
 2     -0.368391      -0.381225          -0.046687               -0.029912
 3     -0.368391      -0.381434          -0.046514               -0.009583
 4     -0.368391      -0.295985          -0.045649                0.005664
 ...         ...            ...                ...                     ...
 43533 -0.368391      -0.381434          -0.046514               -0.009583
 43534  2.527328      -0.381780          -0.046860               -0.024829
 43535 -0.368391      -0.373561          -0.046341               -0.019747
 43536 -0.368391      -0.381405          -0.046514               -0.009583
 43537 -0.368391      -0.381435          -0.046514               -0.009583

        Fwd Packets Length Total  Bwd Packets Length Total  \
 0                     -0.048285                 -0.014162
 1                     -0.043255                 -0.012970
 2                     -0.048285                 -0.014162
 3                     -0.046531                 -0.013711
 4                     -0.042109                 -0.008637
 ...                         ...                       ...
 43533                 -0.046531                 -0.013711
 43534                 -0.048064                 -0.013963
 43535                 -0.048059                 -0.014095
 43536                 -0.046531                 -0.013711
 43537                 -0.046531                 -0.013711

        Fwd Packet Length Max  Fwd Packet Length Min  Fwd Packet Length Mean  \
 0                  -0.829974              -0.283289               -1.027630
 1                   2.150801              -0.283289                1.808440
 2                  -0.829974              -0.283289               -1.027630
 3                   0.209313              -0.283289                0.620425
 4                   1.328299              -0.283289                1.148712
 ...                      ...                    ...                     ...
 43533               0.209313              -0.283289                0.620425
 43534              -0.699266               1.695621               -0.405818
 43535              -0.696078              -0.283289               -0.868385
 43536               0.209313              -0.283289                0.620425
 43537               0.209313              -0.283289                0.620425

        Fwd Packet Length Std  ...  Fwd Act Data Packets  Fwd Seg Size Min  \
 0                  -0.886296  ...             -0.046431          1.327418
 1                   2.371094  ...             -0.046258          1.327418
 2                  -0.886296  ...             -0.046431          1.327418
 3                   0.579927  ...             -0.046258         -0.204643
 4                   0.890858  ...             -0.045566         -0.204643
 ...                      ...  ...                   ...               ...
 43533               0.579927  ...             -0.046258         -0.204643
 43534              -0.886296  ...             -0.046431         -1.736704
 43535              -0.722703  ...             -0.046258         -0.204643
 43536               0.579927  ...             -0.046258         -0.204643
 43537               0.579927  ...             -0.046258         -0.204643

        Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  \
 0        -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 1        -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 2        -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 3        -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 4        -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 ...            ...         ...         ...         ...        ...       ...
 43533    -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 43534    -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 43535    -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 43536    -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961
 43537    -0.067283   -0.050933   -0.077534   -0.057422  -0.291493 -0.084961

        Idle Max  Idle Min
 0     -0.295088  -0.28541
 1     -0.295088  -0.28541
 2     -0.295088  -0.28541
 3     -0.295088  -0.28541
 4     -0.295088  -0.28541
 ...         ...       ...
 43533 -0.295088  -0.28541
 43534 -0.295088  -0.28541
 43535 -0.295088  -0.28541
 43536 -0.295088  -0.28541
 43537 -0.295088  -0.28541

 [43538 rows x 77 columns],
 3988219    1
 4280327    0
 4252004    1
 1895205    1
 6217047    0
           ..
 1843246    1
 5710839    1
 5888604    1
 1844901    1
 1847513    1
 Name: Label_Binary, Length: 43538, dtype: int64)

In [20]:
combined_datasets.head(5)

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,6,888751,11,11,1249,1969.0,736,0,113.545456,220.896072,...,32,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1,0,112642816,3,0,0,0.0,0,0,0.000000,0.000000,...,0,0.0,0.0,0.0,0.0,56300000.0,7.071068,56300000.0,56300000.0,Benign
2,0,112642712,3,0,0,0.0,0,0,0.000000,0.000000,...,0,0.0,0.0,0.0,0.0,56300000.0,18.384777,56300000.0,56300000.0,Benign
3,0,112642648,3,0,0,0.0,0,0,0.000000,0.000000,...,0,0.0,0.0,0.0,0.0,56300000.0,5.656854,56300000.0,56300000.0,Benign
4,0,112642702,3,0,0,0.0,0,0,0.000000,0.000000,...,0,0.0,0.0,0.0,0.0,56300000.0,65.053825,56300000.0,56300000.0,Benign