In [1]:
import sys
sys.path.append("/Users/sujaladhikari/sujalpersonal/Projects/FedIDS")

In [2]:
import os 
import numpy as np 
import pandas as pd 
from torch.utils.data import DataLoader
from torch.utils.data import TensorDataset
import torch 
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from Model.model import MLP
from torch.optim import Adam
import utils
from sklearn.metrics import classification_report
import random 
import pickle

In [3]:
dataset = pd.read_csv('../silos_datasets/combined_binary_silos.csv')
dataset = dataset.drop(columns = 'Unnamed: 0')
dataset.head(5)

# global_scaler = StandardScaler()
# global_X = dataset.drop(columns='Label_Binary').to_numpy()
# global_scaler.fit(global_X)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label_Binary
0,60453,94,1,1,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,0
1,53904,63,1,1,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,0
2,80,83165164,7,6,354,11595,348,0,50.571429,131.172732,...,20,51.0,0.0,51,51,83100000.0,0.0,83100000,83100000,1
3,80,85013328,6,6,361,11595,361,0,60.166667,147.377633,...,32,1014.0,0.0,1014,1014,84900000.0,0.0,84900000,84900000,1
4,80,83303368,8,5,337,11595,337,0,42.125000,119.147493,...,32,1011.0,0.0,1011,1011,83200000.0,0.0,83200000,83200000,1

In [4]:
print(dataset['Label_Binary'].value_counts())
print(f"The dataset has following number {dataset.shape[0]} number of rows and {dataset.shape[1]} number of columns")

Label_Binary
0    556488
1    556488
Name: count, dtype: int64
The dataset has following number 1112976 number of rows and 79 number of columns

In [5]:
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
device
RANDOMSEED = 999
random.seed(RANDOMSEED)
np.random.seed(RANDOMSEED)
torch.manual_seed(RANDOMSEED)
if torch.backends.mps.is_available():
    torch.mps.manual_seed(RANDOMSEED)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
### Creating a generator to pass into the data loader 
g = torch.Generator()
g.manual_seed(RANDOMSEED)

In [6]:
X = dataset.drop(columns = 'Label_Binary')
X = X.to_numpy()
y = dataset['Label_Binary']
y = y.to_numpy()

In [7]:
indices = np.arange(len(dataset))

In [8]:
## Spliting the data into train, test, and validation splits
X_train , X_vals, y_train, y_vals, idx_train, idx_vals = train_test_split(X,y, indices, test_size=0.3, random_state=RANDOMSEED, stratify=y)
X_val, X_test, y_val, y_test, idx_val, idx_test = train_test_split(X_vals, y_vals, idx_vals, test_size=0.5, random_state=RANDOMSEED)

In [9]:
### Standard Scaling for all the datas
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_train_scaled = torch.tensor(X_train_scaled, dtype = torch.float32)
y_train_scaled = torch.tensor(y_train, dtype = torch.long)

X_val_scaled = scaler.transform(X_val)
X_val_scaled = torch.tensor(X_val_scaled, dtype = torch.float32)
y_val_scaled = torch.tensor(y_val, dtype = torch.long)

X_test_scaled = scaler.transform(X_test)
X_test_scaled = torch.tensor(X_test_scaled, dtype = torch.float32)
y_test_scaled = torch.tensor(y_test, dtype = torch.long)

In [10]:
training_data = TensorDataset(X_train_scaled,y_train_scaled)
testing_data = TensorDataset(X_test_scaled, y_test_scaled)
validation_data = TensorDataset(X_val_scaled, y_val_scaled)

In [11]:
training_batch = DataLoader(training_data, batch_size = 64, shuffle = True, generator=g)
testing_batch = DataLoader(testing_data, batch_size=64, shuffle=False)
validation_batch = DataLoader(validation_data,batch_size = 64, shuffle = False)

In [ ]:
### Creating the centralized global test data 
golden_data = []
path = '../centralized_data/centralizedevaluation/'
silos = ['siloOne', 'siloTwo', 'siloThree', 'siloFour']
for i in silos:
    filepath = os.path.join(path, f'{i}_X_test.csv')
    print(filepath)
    testfilepath = os.path.join(path, f'{i}_y_test.csv')
    if os.path.exists(filepath) and os.path.exists(testfilepath):
        x_test_data = pd.read_csv(filepath)
        test_data = pd.read_csv(testfilepath)
        combined_data = pd.concat([x_test_data,test_data], axis = 1)
        golden_data.append(combined_data)

global_dataset = pd.concat(golden_data, ignore_index=True)
## Randomly shuffling the dataset 
global_dataset = global_dataset.sample(frac = 1, random_state = RANDOMSEED).reset_index(drop = True)
global_dataset.to_csv('../datasets/global_test_dataset.csv', index = False)
global_dataset.head(5)

../centralized_data/centralizedevaluation/siloOne_X_test.csv
../centralized_data/centralizedevaluation/siloTwo_X_test.csv
../centralized_data/centralizedevaluation/siloThree_X_test.csv
../centralized_data/centralizedevaluation/siloFour_X_test.csv

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label_Binary
0,123,37439,1,1,48,48,48,48,48.0,0.0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,0
1,80,23093,1,1,0,0,0,0,0.0,0.0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,0
2,53,152327,1,1,42,131,42,42,42.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,0
3,53,148427,2,2,60,452,30,30,30.0,0.0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,0
4,2065,52,1,1,0,6,0,0,0.0,0.0,...,40,0.0,0.0,0,0,0.0,0.0,0,0,1

In [13]:
data = pd.read_csv('../centralized_data/centralizedevaluation/siloOne_X_test.csv')
data.head(5)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
0,53,63520,1,1,42,385,42,42,42.000000,0.00000,...,0,32,0.0,0.0,0,0,0.0,0.0,0,0
1,53,60028,1,1,55,116,55,55,55.000000,0.00000,...,0,20,0.0,0.0,0,0,0.0,0.0,0,0
2,53,61293,2,2,58,166,29,29,29.000000,0.00000,...,1,32,0.0,0.0,0,0,0.0,0.0,0,0
3,80,98255874,6,6,313,11595,295,0,52.166667,118.99986,...,3,20,12990.0,0.0,12990,12990,98200000.0,0.0,98200000,98200000
4,80,4,2,0,0,0,0,0,0.000000,0.00000,...,0,32,0.0,0.0,0,0,0.0,0.0,0,0

In [14]:
print(MLP)

<class 'Model.model.MLP'>

In [15]:
input_size = 78
hidden_layer = [256, 128,64,8]
num_classes = 2

In [16]:
## We will be using the same model that is being used in fedmodel.py for the federated purpose
model = MLP(input_size, hidden_layer, num_classes).to(device)
### Optimizer and loss function 
optimizer = torch.optim.Adam(model.parameters(), lr = 0.001)
loss = nn.CrossEntropyLoss()
num_epoch = 20
model = model.to(device)

In [17]:
### Training, testing and evaluation of the centralized model 
## setting up the training environment:
def train(model, train_loader,validation_loader, criterion, device):
    model.train() ## Starting to train the model 
    training_loss = 0.0 ## Calculating the training loss in terms of floating value
    train_correct = 0 ## Count of total number of correct samples in total 
    training_total = 0 ## Count of the total number of samples checked
    for batch in train_loader: ## Loading the data loader
        samples, classes = batch 
        samples = samples.to(device) ## Converting the sample and classes to the device ('cpu')
        classes = classes.to(device)
        prediciton = model(samples) ## Prediction for the samples in the batch 
        optimizer.zero_grad() ## Started the calculation of the loss 
        loss = criterion(prediciton, classes)
        loss.backward() ## Backward propagation 
        optimizer.step() ## Forward optimizatio 
        training_loss +=loss.item() * samples.size(0) ## Calculating the loss for each batch 
        _,predicted = prediciton.max(1) ## Max prediction for each sample in the batch 
        training_total += classes.size(0) ### Each total in training adds up 
        train_correct += predicted.eq(classes).sum().item() ## Converting the total predicted that are equal to the classes and sum them 
    training_loss = training_loss/len(train_loader.dataset)
    training_accuracy = 100 * train_correct/ training_total 
    val_loss = 0
    val_correct = 0
    val_total = 0 
    model.eval()
    with torch.no_grad(): ## Evaluation started
        for val_batch in validation_loader:
            features, labels = val_batch 
            features = features.to(device) ## Converted the path to device 'cpu'
            labels = labels.to(device)
            val_outputs = model(features) ## Outputs
            val_loss_batch = criterion(val_outputs, labels) ## loss calculated
            val_loss += val_loss_batch.item() * features.size(0) ## for each batch 
            _, val_predicted = val_outputs.max(1) ## Maximum value calcuated
            val_correct += val_predicted.eq(labels).sum().item()
            val_total += labels.size(0) 
    avg_validation_loss = val_loss / len(validation_loader.dataset) ## Average across the sum 
    validation_accuracy = 100 * val_correct/ val_total ## Accuracy 
    return training_loss, training_accuracy , avg_validation_loss, validation_accuracy, val_correct, train_correct

In [18]:
### Creating the evalution function 
def evaluate(model, test_loader, critertion, device):
    model.eval()
    test_loss = 0.0 ## This is for the test loss 
    correct = 0 
    total = 0 
    predictions = []
    true_labels = []
    with torch.no_grad():
        for batch in test_loader:
            samples, labels = batch 
            samples = samples.to(device)
            labels = labels.to(device)
            outputs = model(samples)
            loss = critertion(outputs, labels)
            _, predicted = outputs.max(1)
            test_loss += loss.item() * samples.size(0)
            total += labels.size(0)
            correct += predicted.eq(labels).sum().item()
            predictions.extend(predicted.tolist())
            true_labels.extend(labels.tolist())
        
    test_loss = test_loss / len(test_loader.dataset)
    accuracy = 100 * correct / total 

    return test_loss, accuracy, predictions, true_labels

### Since the training process has been done, we will evaluate the model's perfomance

In [19]:
### On the given epoch we will be training and testing the epcoh 
num_epoch
for epoch in range(num_epoch):
    training_loss, training_accuracy , avg_validation_loss, validation_accuracy, val_correct, train_correct = train(model, training_batch,validation_batch, loss, device)
    test_loss, test_accuracy, predictions, true_labels = evaluate(model, testing_batch, loss, device)
    print(f"Epoch [{epoch+1}/{num_epoch}], Training Loss: {training_loss:4f}, Testing Loss: {test_loss:4f}")
    report = classification_report(true_labels, predictions)
    print(report)

KeyboardInterrupt:

### Lets evaluate how does the model do in each silos

In [ ]:
def silos_evaluate(model, batch, criterion, device):
    model.eval()
    test_loss = 0.0
    total = 0 
    corrected = 0
    predictions = []
    true_labels = []
    for samples, features in batch:
        samples = samples.to(device)
        features = features.to(device)
        outputs = model(samples)
        loss = criterion(outputs, features)
        _, predicted = outputs.max(1)
        total += features.size(0)
        test_loss += loss.item() * samples.size(0)
        corrected += predicted.eq(features).sum().item()
        predictions.extend(predicted.tolist())
        true_labels.extend(features.tolist())
    
    test_loss = test_loss / len(batch.dataset)
    accuracy = 100 * corrected/total

    return test_loss, accuracy, predictions, true_labels

In [ ]:
silo_lengths = [
    len(pd.read_csv('../silos_datasets/siloBinaryOne.csv')),
    len(pd.read_csv('../silos_datasets/siloBinaryTwo.csv')),
    len(pd.read_csv('../silos_datasets/siloBinaryThree.csv')),
    len(pd.read_csv('../silos_datasets/siloBinaryFour.csv')),
]
print(silo_lengths)

[503424, 577570, 27664, 4318]

In [ ]:
silo_boundaries = np.cumsum([0] + silo_lengths)
print(silo_boundaries)

[      0  503424 1080994 1108658 1112976]

In [ ]:
X = dataset.drop(columns = 'Label_Binary')
y = dataset['Label_Binary']

In [ ]:
def silo_eval_batch(silo_idx): ## we are creating batch od data that contain silo 3 and have never been seen by the centralized model 
    low, high = silo_boundaries[silo_idx], silo_boundaries[silo_idx+1] ## This is the index of each silos_evaluate
    silo_test_idx = idx_test[(idx_test>=low) &(idx_test < high)]
    X_silo =X.iloc[silo_test_idx].to_numpy()
    y_silo = y.iloc[silo_test_idx].to_numpy()
    X_silo = scaler.transform(X_silo)
    X_silo = torch.tensor(X_silo, dtype = torch.float32)
    y_silo = torch.tensor(y_silo, dtype = torch.long)
    return DataLoader(TensorDataset(X_silo, y_silo), batch_size=64, shuffle = False)

In [ ]:
silos = ['Silo One', 'Silo Two', 'Silo Three', 'Silo Four']
for i, name in enumerate(silos):
    silo_batch = silo_eval_batch(i)
    test_loss, test_accuracy, predictions, true_labels = silos_evaluate(model, silo_batch, loss, device)
    print(f"{name}")
    print(f"Test Loss:{test_loss}, Test Accuracy:{test_accuracy}")
    print(classification_report(true_labels, predictions))

Silo One
Test Loss:0.016262512851442323, Test Accuracy:99.57486698089542
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     37717
           1       0.99      1.00      1.00     38024

    accuracy                           1.00     75741
   macro avg       1.00      1.00      1.00     75741
weighted avg       1.00      1.00      1.00     75741

Silo Two
Test Loss:0.01894711170882438, Test Accuracy:99.50668179817959
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     43343
           1       0.99      1.00      1.00     43011

    accuracy                           1.00     86354
   macro avg       1.00      1.00      1.00     86354
weighted avg       1.00      1.00      1.00     86354

Silo Three
Test Loss:0.01980332235924347, Test Accuracy:99.17655606684427
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      2087
           1       0.99      0.99      0.99      2042

    accuracy                           0.99      4129
   macro avg       0.99      0.99      0.99      4129
weighted avg       0.99      0.99      0.99      4129

Silo Four
Test Loss:0.30639981555740864, Test Accuracy:59.75103734439834
              precision    recall  f1-score   support

           0       0.57      1.00      0.73       391
           1       0.98      0.13      0.22       332

    accuracy                           0.60       723
   macro avg       0.78      0.56      0.48       723
weighted avg       0.76      0.60      0.50       723

In [ ]:
## Turning the model into pickel file 
path = '../models/'
log_path = os.path.join(path, 'centralized_model.pickle')
utils.savein_pickle(log_path, model)