In [84]:
import pandas as pd 
import os 
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pickle

In [85]:
RANDOM_SEED = 999

In [86]:
### Combining all the datasets 
silo_path = '../silos_datasets/'
datasets = []

for filename in os.listdir(silo_path):
    if filename.endswith('.csv'):
        filepath = os.path.join(silo_path, filename) ### Creating a file path for each directory
        data = pd.read_csv(filepath)
        datasets.append(data)
    
combined_datasets = pd.concat(datasets, ignore_index=True)
combined_datasets.head(5)

    Destination Port   Flow Duration  ...  Label_Binary  Unnamed: 0
0            60453.0            94.0  ...           NaN         NaN
1            53904.0            63.0  ...           NaN         NaN
2               80.0      83165164.0  ...           NaN         NaN
3               80.0      85013328.0  ...           NaN         NaN
4               80.0      83303368.0  ...           NaN         NaN

[5 rows x 81 columns]

In [87]:
print(combined_datasets[' Label'].value_counts())
attack_data = combined_datasets[combined_datasets[' Label'] != 'BENIGN']
non_attack_data = combined_datasets[combined_datasets[' Label'] == 'BENIGN']
print("----------")
print(f" Total attack samples are {attack_data.shape[0]}")
print(f"Total non-attack samples are {non_attack_data.shape[0]}")

 Label
BENIGN                    556488
DoS Hulk                  230124
PortScan                  158804
DDoS                      128025
DoS GoldenEye              10293
FTP-Patator                 7935
SSH-Patator                 5897
DoS slowloris               5796
DoS Slowhttptest            5499
Bot                         1956
Web Attack Brute Force      1507
Web Attack XSS               652
Name: count, dtype: int64
----------
 Total attack samples are 4911266
Total non-attack samples are 556488

In [88]:
### Binary classed for each of the silos 
pd1 = pd.read_csv('../silos_datasets/siloOne.csv')
pd1

        Destination Port  Flow Duration  ...  Idle Min             Label
0                  60453             94  ...         0            BENIGN
1                  53904             63  ...         0            BENIGN
2                     80       83165164  ...  83100000          DoS Hulk
3                     80       85013328  ...  84900000          DoS Hulk
4                     80       83303368  ...  83200000          DoS Hulk
...                  ...            ...  ...       ...               ...
503419                80       63095538  ...   8023641  DoS Slowhttptest
503420                80            218  ...         0          DoS Hulk
503421               443        2087714  ...         0            BENIGN
503422                80       60492231  ...   9976221            BENIGN
503423                53          31971  ...         0            BENIGN

[503424 rows x 79 columns]

In [89]:
print(pd1[' Label'].value_counts())

 Label
BENIGN              251712
DoS Hulk            230124
DoS GoldenEye        10293
DoS slowloris         5796
DoS Slowhttptest      5499
Name: count, dtype: int64

In [90]:
pd2 = pd.read_csv('../silos_datasets/siloTwo.csv')
pd2.head(5)

   Destination Port  Flow Duration  ...  Idle Min     Label
0             52742          26932  ...         0    BENIGN
1             39839             52  ...         0    BENIGN
2              5950             48  ...         0  PortScan
3                53            411  ...         0    BENIGN
4               705             11  ...         0  PortScan

[5 rows x 79 columns]

In [91]:
print(pd2[' Label'].value_counts())

 Label
BENIGN      288785
PortScan    158804
DDoS        128025
Bot           1956
Name: count, dtype: int64

In [92]:
pd3 = pd.read_csv('../silos_datasets/siloThree.csv')
pd3.head(5)

   Destination Port  Flow Duration  ...  Idle Min        Label
0                21            221  ...         0  FTP-Patator
1                53         612792  ...         0       BENIGN
2               443      110219468  ...   9850722       BENIGN
3                53          37750  ...         0       BENIGN
4                88            755  ...         0       BENIGN

[5 rows x 79 columns]

In [93]:
print(pd3[' Label'].value_counts())

 Label
BENIGN         13832
FTP-Patator     7935
SSH-Patator     5897
Name: count, dtype: int64

In [94]:
pd4 = pd.read_csv('../silos_datasets/siloFour.csv')
pd4.head(5)

   Destination Port  Flow Duration  ...  Idle Min           Label
0                80      117286545  ...  10000000          BENIGN
1                80        5243646  ...         0  Web Attack XSS
2                53          31216  ...         0          BENIGN
3                53          31368  ...         0          BENIGN
4               443       61143903  ...   9298227          BENIGN

[5 rows x 79 columns]

In [95]:
print(pd4[' Label'].value_counts())

 Label
BENIGN                    2159
Web Attack Brute Force    1507
Web Attack XSS             652
Name: count, dtype: int64

### Silo 4 contributes fewer samples due to the natural scarcity of web attack traffic, reflecting real world heterogenity in federated environments.

### Converting all the silos to binary

In [96]:
def binary_silos_converter(df):
    df = df.copy()
    df['Label_Binary'] = df[' Label'].apply(lambda x: 0 if x == 'BENIGN' else 1)
    df = df.drop(columns = ' Label')
    return df

In [97]:
pd1_binary = binary_silos_converter(pd1)
print(pd1_binary['Label_Binary'].value_counts())
pd1_binary.to_csv('../silos_datasets/SiloBinaryOne.csv', index = False)

Label_Binary
0    251712
1    251712
Name: count, dtype: int64

In [98]:
### Creating the pd2_binary 
pd2_binary = binary_silos_converter(pd2)
print(pd2_binary['Label_Binary'].value_counts())
pd2_binary.to_csv('../silos_datasets/SiloBinaryTwo.csv', index = False)

Label_Binary
0    288785
1    288785
Name: count, dtype: int64

In [99]:
pd3_binary = binary_silos_converter(pd3)
print(pd3_binary['Label_Binary'].value_counts())
pd3_binary.to_csv('../silos_datasets/SiloBinaryThree.csv', index = False)

Label_Binary
1    13832
0    13832
Name: count, dtype: int64

In [100]:
pd4_binary = binary_silos_converter(pd4)
print(pd4_binary['Label_Binary'].value_counts())
pd4_binary.to_csv('../silos_datasets/SiloBinaryFour.csv', index = False)

Label_Binary
0    2159
1    2159
Name: count, dtype: int64

In [101]:
## Creating the combined dataset
binary_combined_dataset = pd.concat([pd1_binary, pd2_binary, pd3_binary, pd4_binary], ignore_index = True)
binary_combined_dataset.to_csv('../silos_datasets/combined_binary_silos.csv')

In [102]:
binary_combined_dataset.head(5)

    Destination Port   Flow Duration  ...   Idle Min  Label_Binary
0              60453              94  ...          0             0
1              53904              63  ...          0             0
2                 80        83165164  ...   83100000             1
3                 80        85013328  ...   84900000             1
4                 80        83303368  ...   83200000             1

[5 rows x 79 columns]

---
### Getting the train_test split done for every binary silos created

In [ ]:
from sklearn.model_selection import train_test_split ## Imported the train test split library

def train_validation_test(data, silo_name, random_state = RANDOM_SEED):
    scaler = StandardScaler()
    X = data.drop(columns=['Label_Binary'])
    y = data['Label_Binary']
    silo_path = '../silos_datasets/'
    X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3,random_state=random_state, stratify = y)
    X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size = 0.5, random_state=random_state, stratify=y_temp)
    X_test_raw = pd.DataFrame(X_test, columns=X.columns)
    y_test_raw = pd.DataFrame(y_test, columns=y.columns)
    path = '../centralized_data/centralizedevaluation/'
    filename = f'{path}{silo_name}.csv'
    X_test_raw.to_csv(filename, index=False)
    X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns)
    X_val_scaled = pd.DataFrame(scaler.transform(X_val), columns=X_val.columns)
    X_test_scaled = pd.DataFrame(scaler.transform(X_test), columns=X_test.columns)
    X_train_scaled.to_csv(f'{silo_path}{silo_name}_X_train.csv', index=False)
    y_train.to_csv(f'{silo_path}{silo_name}_y_train.csv', index=False)
    X_test_scaled.to_csv(f'{silo_path}{silo_name}_X_test.csv', index=False)
    y_test.to_csv(f'{silo_path}{silo_name}_y_test.csv', index=False)
    X_val_scaled.to_csv(f'{silo_path}{silo_name}_X_val.csv', index=False)
    y_val.to_csv(f'{silo_path}{silo_name}_y_val.csv', index=False)

    return X_train_scaled, y_train, X_test_scaled, y_test, X_val_scaled, y_val

In [104]:
train_validation_test(pd1_binary,'siloOne')
train_validation_test(pd2_binary,'siloTwo')
train_validation_test(pd3_binary,'siloThree')
train_validation_test(pd4_binary,'siloFour')

(      Destination Port  Flow Duration  ...  Idle Max  Idle Min
 0             3.268903      -0.394739  ... -0.181912 -0.177077
 1            -0.321699      -0.122285  ... -0.181912 -0.177077
 2            -0.321699      -0.124625  ... -0.181912 -0.177077
 3            -0.323484      -0.391205  ... -0.181912 -0.177077
 4            -0.297701      -0.387168  ... -0.181912 -0.177077
 ...                ...            ...  ...       ...       ...
 3017         -0.321699      -0.149260  ... -0.181912 -0.177077
 3018         -0.321699      -0.122574  ... -0.181912 -0.177077
 3019          2.922741      -0.394735  ... -0.181912 -0.177077
 3020         -0.321699       1.265133  ... -0.181912 -0.177077
 3021         -0.323484      -0.392938  ... -0.181912 -0.177077

 [3022 rows x 78 columns],
 2383    0
 1019    1
 1746    1
 327     0
 1090    0
        ..
 521     1
 2891    1
 2609    0
 1363    1
 413     0
 Name: Label_Binary, Length: 3022, dtype: int64,
      Destination Port  Flow Duration  ...  Idle Max  Idle Min
 0           -0.321699      -0.394735  ... -0.181912 -0.177077
 1           -0.321699      -0.150809  ... -0.181912 -0.177077
 2           -0.321699      -0.133135  ... -0.181912 -0.177077
 3           -0.321699       5.151178  ...  0.995526  1.075693
 4           -0.297701       5.192596  ...  1.019074  1.083579
 ..                ...            ...  ...       ...       ...
 643         -0.323484      -0.391333  ... -0.181912 -0.177077
 644         -0.321699      -0.392414  ... -0.181912 -0.177077
 645         -0.321699      -0.119673  ... -0.181912 -0.177077
 646         -0.321699      -0.136376  ... -0.181912 -0.177077
 647          0.301273      -0.394737  ... -0.181912 -0.177077

 [648 rows x 78 columns],
 2949    1
 3377    1
 2601    1
 1445    0
 3589    0
        ..
 571     0
 4078    0
 3932    1
 2872    1
 1871    0
 Name: Label_Binary, Length: 648, dtype: int64,
      Destination Port  Flow Duration  ...  Idle Max  Idle Min
 0           -0.323484      -0.393610  ... -0.181912 -0.177077
 1           -0.321699      -0.123250  ... -0.181912 -0.177077
 2           -0.260149      -0.394736  ... -0.181912 -0.177077
 3           -0.321699      -0.137748  ... -0.181912 -0.177077
 4           -0.321699      -0.139889  ... -0.181912 -0.177077
 ..                ...            ...  ...       ...       ...
 643         -0.323484      -0.394731  ... -0.181912 -0.177077
 644         -0.323484      -0.391823  ... -0.181912 -0.177077
 645         -0.297701      -0.335679  ... -0.181912 -0.177077
 646         -0.321699      -0.391485  ... -0.181912 -0.177077
 647         -0.321699       1.188242  ... -0.181912 -0.177077

 [648 rows x 78 columns],
 3713    0
 1570    1
 2113    0
 2708    1
 3101    1
        ..
 768     0
 56      0
 1585    0
 1864    0
 4112    1
 Name: Label_Binary, Length: 648, dtype: int64)