In [2]:
import pandas as pd 
import os 
import numpy as np

In [5]:
### Combining all the datasets 
silo_path = '../silos_datasets/'
datasets = []

for filename in os.listdir(silo_path):
    if filename.endswith('.csv'):
        filepath = os.path.join(silo_path, filename) ### Creating a file path for each directory
        data = pd.read_csv(filepath)
        datasets.append(data)
    
combined_datasets = pd.concat(datasets, ignore_index=True)
combined_datasets.head(5)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,60453,94,1,1,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,53904,63,1,1,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,80,83165164,7,6,354,11595,348,0,50.571429,131.172732,...,20,51.0,0.0,51,51,83100000.0,0.0,83100000,83100000,DoS Hulk
3,80,85013328,6,6,361,11595,361,0,60.166667,147.377633,...,32,1014.0,0.0,1014,1014,84900000.0,0.0,84900000,84900000,DoS Hulk
4,80,83303368,8,5,337,11595,337,0,42.125000,119.147493,...,32,1011.0,0.0,1011,1011,83200000.0,0.0,83200000,83200000,DoS Hulk

In [14]:
print(combined_datasets[' Label'].value_counts())
attack_data = combined_datasets[combined_datasets[' Label'] != 'BENIGN']
non_attack_data = combined_datasets[combined_datasets[' Label'] == 'BENIGN']
print("----------")
print(f" Total attack samples are {attack_data.shape[0]}")
print(f"Total non-attack samples are {non_attack_data.shape[0]}")

 Label
BENIGN                    556488
DoS Hulk                  230124
PortScan                  158804
DDoS                      128025
DoS GoldenEye              10293
FTP-Patator                 7935
SSH-Patator                 5897
DoS slowloris               5796
DoS Slowhttptest            5499
Bot                         1956
Web Attack Brute Force      1507
Web Attack XSS               652
Name: count, dtype: int64
----------
 Total attack samples are 556488
Total non-attack samples are 556488

In [17]:
### Binary classed for each of the silos 
pd0 = pd.read_csv('../silos_datasets/siloOne.csv')
pd0

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,60453,94,1,1,0,0,0,0,0.000000,0.000000,...,32,0.000000e+00,0.0000,0,0,0.000000e+00,0.000000e+00,0,0,BENIGN
1,53904,63,1,1,0,0,0,0,0.000000,0.000000,...,32,0.000000e+00,0.0000,0,0,0.000000e+00,0.000000e+00,0,0,BENIGN
2,80,83165164,7,6,354,11595,348,0,50.571429,131.172732,...,20,5.100000e+01,0.0000,51,51,8.310000e+07,0.000000e+00,83100000,83100000,DoS Hulk
3,80,85013328,6,6,361,11595,361,0,60.166667,147.377633,...,32,1.014000e+03,0.0000,1014,1014,8.490000e+07,0.000000e+00,84900000,84900000,DoS Hulk
4,80,83303368,8,5,337,11595,337,0,42.125000,119.147493,...,32,1.011000e+03,0.0000,1011,1011,8.320000e+07,0.000000e+00,83200000,83200000,DoS Hulk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503419,80,63095538,7,0,0,0,0,0,0.000000,0.000000,...,40,7.008270e+06,0.0000,7008270,7008270,1.870000e+07,1.220000e+07,32000000,8023641,DoS Slowhttptest
503420,80,218,2,0,0,0,0,0,0.000000,0.000000,...,32,0.000000e+00,0.0000,0,0,0.000000e+00,0.000000e+00,0,0,DoS Hulk
503421,443,2087714,11,6,1045,1375,432,0,95.000000,158.564813,...,32,0.000000e+00,0.0000,0,0,0.000000e+00,0.000000e+00,0,0,BENIGN
503422,80,60492231,10,10,430,168,382,0,43.000000,119.127383,...,20,6.517517e+04,35992.9829,138645,50332,9.996616e+06,1.013091e+04,10000000,9976221,BENIGN
503423,53,31971,2,2,66,190,33,33,33.000000,0.000000,...,20,0.000000e+00,0.0000,0,0,0.000000e+00,0.000000e+00,0,0,BENIGN

In [18]:
print(pd0[' Label'].value_counts())

 Label
BENIGN              251712
DoS Hulk            230124
DoS GoldenEye        10293
DoS slowloris         5796
DoS Slowhttptest      5499
Name: count, dtype: int64