In [105]:
import pandas as pd 
import os 
import numpy as np

In [106]:
RANDOM_SEED = 42
daily_dataset_directory = '../datasets/'
dataset = []
for filename in os.listdir(daily_dataset_directory):
    if filename.endswith('.csv'):
        file_path = os.path.join(daily_dataset_directory, filename)
        data = pd.read_csv(file_path)
        dataset.append(data)

centralized_data  = pd.concat(dataset, ignore_index= True)

### Preprocessing the combined dataset

In [107]:
print(f"The combined dataset has {centralized_data .shape[0]} number of samples and {centralized_data .shape[1]} number of features")
centralized_data .head(5)

The combined dataset has 2830743 number of samples and 79 number of features

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,166,1,1,0,0,0,0,0.0,0.0,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
1,60148,83,1,2,0,0,0,0,0.0,0.0,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
2,123,99947,1,1,48,48,48,48,48.0,0.0,...,40,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
3,123,37017,1,1,48,48,48,48,48.0,0.0,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
4,0,111161336,147,0,0,0,0,0,0.0,0.0,...,0,1753752.625,2123197.578,4822992,95,9463032.7,2657727.996,13600000,5700287,BENIGN

In [108]:
centralized_data.replace([np.inf, -np.inf], np.nan, inplace=True)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,166,1,1,0,0,0,0,0.000000,0.000000,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
1,60148,83,1,2,0,0,0,0,0.000000,0.000000,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
2,123,99947,1,1,48,48,48,48,48.000000,0.000000,...,40,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
3,123,37017,1,1,48,48,48,48,48.000000,0.000000,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
4,0,111161336,147,0,0,0,0,0,0.000000,0.000000,...,0,1753752.625,2123197.578,4822992,95,9463032.7,2657727.996,13600000,5700287,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2830738,55641,49,1,3,6,18,6,6,6.000000,0.000000,...,20,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
2830739,45337,217,2,1,31,6,31,0,15.500000,21.920310,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
2830740,22,1387547,41,46,2728,6634,456,0,66.536585,110.129945,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
2830741,22,207,1,1,0,0,0,0,0.000000,0.000000,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
2830742,60146,50,1,2,0,0,0,0,0.000000,0.000000,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN

In [109]:
print(centralized_data.columns)

Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min',
       ' Label'],
      dtype='str')

In [110]:
centralized_data  = centralized_data .replace({
    'Web Attack � Brute Force': 'Web Attack Brute Force',
    'Web Attack � XSS': 'Web Attack XSS',
    'Web Attack � Sql Injection': 'Web Attack SQL Injection'
})

In [111]:
## Class types in the Label column 
print(centralized_data [' Label'].value_counts())

 Label
BENIGN                      2273097
DoS Hulk                     231073
PortScan                     158930
DDoS                         128027
DoS GoldenEye                 10293
FTP-Patator                    7938
SSH-Patator                    5897
DoS slowloris                  5796
DoS Slowhttptest               5499
Bot                            1966
Web Attack Brute Force         1507
Web Attack XSS                  652
Infiltration                     36
Web Attack SQL Injection         21
Heartbleed                       11
Name: count, dtype: int64

### Checking the number of the null values in the entire dataset

In [112]:
centralized_data .dropna(subset=['Flow Bytes/s'], inplace = True)
print(centralized_data .isna().sum().to_list())

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [113]:
print(f"Centralized Data has {centralized_data.shape[0]} number of samples and {centralized_data.shape[1]} number of features")

Centralized Data has 2827876 number of samples and 79 number of features

### Stratified Downsampling -> To increase the processing speed on the calculation, by downsampling the rows and keeping the same class distribution structure.

In [114]:
def stratifying_datasets(data, label, ratio):
    grouped = data.groupby(label)
    subset = []
    for label, group in grouped:
        num_samples = int(len(group) * ratio)
        sampled_group  = group.sample(n = num_samples, random_state= RANDOM_SEED)
        subset.append(sampled_group)
    
    return subset

In [115]:
subset = stratifying_datasets(centralized_data, ' Label', 0.46)
subset_centralized = pd.concat(subset, ignore_index=True)
subset_centralized.head(5)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,49,2,0,0,0,0,0,0.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,53,279,2,2,70,692,35,35,35.0,0.0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,888,84,2,2,4,12,2,2,2.0,0.0,...,24,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,53,64877,1,1,55,110,55,55,55.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,60385,61,1,1,0,0,0,0,0.0,0.0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [116]:
### Value counts of the label 
print(subset_centralized[' Label'].value_counts())

 Label
BENIGN                      1044807
DoS Hulk                     105857
PortScan                      73049
DDoS                          58891
DoS GoldenEye                  4734
FTP-Patator                    3650
SSH-Patator                    2712
DoS slowloris                  2666
DoS Slowhttptest               2529
Bot                             899
Web Attack Brute Force          693
Web Attack XSS                  299
Infiltration                     16
Web Attack SQL Injection          9
Heartbleed                        5
Name: count, dtype: int64

### Reduced the number of rows by keeping the same class imbalance.

In [117]:
### Since we are creating the four silos, we will be splitting the entire dataset into 4 different silos with the proper non-IID approach 

non_attack_data = subset_centralized[subset_centralized[' Label'] == 'BENIGN'].copy()
attack_data = subset_centralized[subset_centralized[' Label'] != 'BENIGN'].copy()

### Creating the silos out of the stratified dataset

In [118]:
benign_silos = np.array_split(non_attack_data.sample(frac = 1, random_state=RANDOM_SEED),4)

In [119]:
benign_silosOne = pd.DataFrame(benign_silos[0], columns=subset_centralized.columns)
benign_silosTwo = pd.DataFrame(benign_silos[1], columns=subset_centralized.columns)
benign_silosThree = pd.DataFrame(benign_silos[2], columns=subset_centralized.columns)
benign_silosFour = pd.DataFrame(benign_silos[3], columns=subset_centralized.columns)

In [120]:
silos_config = {
    1:{
        'attacks': ['DoS Hulk', 'DoS GoldenEye', 'DoS slowloris', 'DoS Slowhttptest'],
        'benign': benign_silosOne
    },
    2:{
        'attacks':['PortScan', 'DDos', 'Bot'],
        'benign': benign_silosTwo
    },
    3:{
        'attacks':['FTP-Patator', 'SSH-Patator', 'Heartbleed'],
        'benign':benign_silosThree
    },
    4:{
        'attacks':['Web Attack Brute Force', 'Web Attack XSS', 'Web Attack SQL Injection', 'Infiltration'],
        'benign':benign_silosFour
    }
}

In [121]:
siloOneConfig = attack_data[attack_data[' Label'].isin(silos_config[1]['attacks'])]
siloOne = pd.concat([siloOneConfig, benign_silosOne], ignore_index=True)
print(siloOne[' Label'].value_counts())
siloOne.to_csv('../silos_datasets/siloOne.csv')

 Label
BENIGN              261202
DoS Hulk            105857
DoS GoldenEye         4734
DoS slowloris         2666
DoS Slowhttptest      2529
Name: count, dtype: int64

In [122]:
siloTwoConfig = attack_data[attack_data[' Label'].isin(silos_config[2]['attacks'])]
siloTwo = pd.concat([siloTwoConfig, benign_silosTwo], ignore_index=True)
print(siloTwo[' Label'].value_counts())
siloTwo.to_csv('../silos_datasets/siloTwo.csv')

 Label
BENIGN      261202
PortScan     73049
Bot            899
Name: count, dtype: int64

In [123]:
siloThreeConfig = attack_data[attack_data[' Label'].isin(silos_config[3]['attacks'])]
siloThree = pd.concat([siloThreeConfig, benign_silosThree], ignore_index=True)
print(siloThree[' Label'].value_counts())
siloThree.to_csv('../silos_datasets/siloThree.csv')

 Label
BENIGN         261202
FTP-Patator      3650
SSH-Patator      2712
Heartbleed          5
Name: count, dtype: int64

In [124]:
siloFourConfig = attack_data[attack_data[' Label'].isin(silos_config[4]['attacks'])]
siloFour = pd.concat([siloFourConfig, benign_silosFour], ignore_index=True)
print(siloFour[' Label'].value_counts())
siloFour.to_csv('../silos_datasets/siloFour.csv')

 Label
BENIGN                      261201
Web Attack Brute Force         693
Web Attack XSS                 299
Infiltration                    16
Web Attack SQL Injection         9
Name: count, dtype: int64

### Binary Conversion of the entire dataset

In [125]:
siloOne['Label_Bin'] = siloOne[' Label'].apply(lambda x: 0 if x == 'BENIGN' else 1)

In [126]:
siloOne.drop(columns=' Label', inplace=True)
siloOne.head(5)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label_Bin
0,80,7744936,8,6,510,11632,510,0,63.75,180.312229,...,32,0.0,0.0,0,0,0.0,0.0,0,0,1
1,80,10930608,5,4,345,3525,345,0,69.0,154.28869,...,32,699.0,0.0,699,699,5927499.0,0.0,5927499,5927499,1
2,80,11480771,8,5,380,11632,380,0,47.5,134.350288,...,32,961.0,0.0,961,961,6474936.0,0.0,6474936,6474936,1
3,80,11872818,5,5,421,3525,421,0,84.2,188.276924,...,32,911.0,0.0,911,911,6863297.0,0.0,6863297,6863297,1
4,80,5008443,8,8,374,11632,374,0,46.75,132.228968,...,32,0.0,0.0,0,0,0.0,0.0,0,0,1

In [127]:
print(siloOne['Label_Bin'].value_counts())

Label_Bin
0    261202
1    115786
Name: count, dtype: int64

In [128]:
### Similary, 
siloTwo['Label_Bin'] = siloTwo[' Label'].apply(lambda x: 0 if x == 'BENIGN' else 1)
siloTwo.drop(columns=' Label', inplace=True)
siloThree['Label_Bin'] = siloThree[' Label'].apply(lambda x: 0 if x == 'BENIGN' else 1)
siloThree.drop(columns=' Label', inplace=True)
siloFour['Label_Bin'] = siloFour[' Label'].apply(lambda x: 0 if x == 'BENIGN' else 1)
siloFour.drop(columns=' Label', inplace=True)