In [157]:
import pandas as pd 
import os 
import numpy as np

In [158]:
RANDOM_SEED = 42
daily_dataset_directory = '../datasets/'
dataset = []
for filename in os.listdir(daily_dataset_directory):
    if filename.endswith('.csv'):
        file_path = os.path.join(daily_dataset_directory, filename)
        data = pd.read_csv(file_path)
        dataset.append(data)

centralized_data  = pd.concat(dataset, ignore_index= True)

### Preprocessing the combined dataset

In [159]:
print(f"The combined dataset has {centralized_data .shape[0]} number of samples and {centralized_data .shape[1]} number of features")
centralized_data .head(5)

The combined dataset has 2830743 number of samples and 79 number of features

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,166,1,1,0,0,0,0,0.0,0.0,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
1,60148,83,1,2,0,0,0,0,0.0,0.0,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
2,123,99947,1,1,48,48,48,48,48.0,0.0,...,40,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
3,123,37017,1,1,48,48,48,48,48.0,0.0,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
4,0,111161336,147,0,0,0,0,0,0.0,0.0,...,0,1753752.625,2123197.578,4822992,95,9463032.7,2657727.996,13600000,5700287,BENIGN

In [160]:
centralized_data.replace([np.inf, -np.inf], np.nan, inplace=True)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,166,1,1,0,0,0,0,0.000000,0.000000,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
1,60148,83,1,2,0,0,0,0,0.000000,0.000000,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
2,123,99947,1,1,48,48,48,48,48.000000,0.000000,...,40,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
3,123,37017,1,1,48,48,48,48,48.000000,0.000000,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
4,0,111161336,147,0,0,0,0,0,0.000000,0.000000,...,0,1753752.625,2123197.578,4822992,95,9463032.7,2657727.996,13600000,5700287,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2830738,55641,49,1,3,6,18,6,6,6.000000,0.000000,...,20,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
2830739,45337,217,2,1,31,6,31,0,15.500000,21.920310,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
2830740,22,1387547,41,46,2728,6634,456,0,66.536585,110.129945,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
2830741,22,207,1,1,0,0,0,0,0.000000,0.000000,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN
2830742,60146,50,1,2,0,0,0,0,0.000000,0.000000,...,32,0.000,0.000,0,0,0.0,0.000,0,0,BENIGN

In [161]:
print(centralized_data.columns)

Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min',
       ' Label'],
      dtype='str')

In [162]:
centralized_data  = centralized_data .replace({
    'Web Attack � Brute Force': 'Web Attack Brute Force',
    'Web Attack � XSS': 'Web Attack XSS',
    'Web Attack � Sql Injection': 'Web Attack SQL Injection'
})

In [163]:
## Class types in the Label column 
print(centralized_data [' Label'].value_counts())

 Label
BENIGN                      2273097
DoS Hulk                     231073
PortScan                     158930
DDoS                         128027
DoS GoldenEye                 10293
FTP-Patator                    7938
SSH-Patator                    5897
DoS slowloris                  5796
DoS Slowhttptest               5499
Bot                            1966
Web Attack Brute Force         1507
Web Attack XSS                  652
Infiltration                     36
Web Attack SQL Injection         21
Heartbleed                       11
Name: count, dtype: int64

### Checking the number of the null values in the entire dataset

In [164]:
centralized_data .dropna(subset=['Flow Bytes/s'], inplace = True)
print(centralized_data .isna().sum().to_list())

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [165]:
print(f"Centralized Data has {centralized_data.shape[0]} number of samples and {centralized_data.shape[1]} number of features")

Centralized Data has 2827876 number of samples and 79 number of features

### Reduced the number of rows by keeping the same class imbalance.

In [166]:
### Since we are creating the four silos, we will be splitting the entire dataset into 4 different silos with the proper non-IID approach 

non_attack_data = centralized_data[centralized_data[' Label'] == 'BENIGN'].copy()
attack_data = centralized_data[centralized_data[' Label'] != 'BENIGN'].copy()

### Creating the silos out of the stratified dataset

In [174]:
benign_silos = np.array_split(non_attack_data.sample(frac = 0.7, random_state=RANDOM_SEED),4)

In [168]:
benign_silosOne = pd.DataFrame(benign_silos[0], columns=centralized_data.columns)
benign_silosTwo = pd.DataFrame(benign_silos[1], columns=centralized_data.columns)
benign_silosThree = pd.DataFrame(benign_silos[2], columns=centralized_data.columns)
benign_silosFour = pd.DataFrame(benign_silos[3], columns=centralized_data.columns)

In [169]:
silos_config = {
    1:{
        'attacks': ['DoS Hulk', 'DoS GoldenEye', 'DoS slowloris', 'DoS Slowhttptest'],
        'benign': benign_silosOne
    },
    2:{
        'attacks':['PortScan', 'DDoS', 'Bot'],
        'benign': benign_silosTwo
    },
    3:{
        'attacks':['FTP-Patator', 'SSH-Patator', 'Heartbleed'],
        'benign':benign_silosThree
    },
    4:{
        'attacks':['Web Attack Brute Force', 'Web Attack XSS', 'Web Attack SQL Injection', 'Infiltration'],
        'benign':benign_silosFour
    }
}

In [ ]:
siloOneConfig = attack_data[attack_data[' Label'].isin(silos_config[1]['attacks'])]
siloOne = pd.concat([siloOneConfig, benign_silosOne], ignore_index=True)
print(siloOne[' Label'].value_counts())

 Label
BENIGN              454264
DoS Hulk            230124
DoS GoldenEye        10293
DoS slowloris         5796
DoS Slowhttptest      5499
Name: count, dtype: int64

In [ ]:
siloTwoConfig = attack_data[attack_data[' Label'].isin(silos_config[2]['attacks'])]
siloTwo = pd.concat([siloTwoConfig, benign_silosTwo], ignore_index=True)
print(siloTwo[' Label'].value_counts())

 Label
BENIGN      454264
PortScan    158804
DDoS        128025
Bot           1956
Name: count, dtype: int64

In [ ]:
siloThreeConfig = attack_data[attack_data[' Label'].isin(silos_config[3]['attacks'])]
siloThree = pd.concat([siloThreeConfig, benign_silosThree], ignore_index=True)
print(siloThree[' Label'].value_counts())

 Label
BENIGN         454264
FTP-Patator      7935
SSH-Patator      5897
Heartbleed         11
Name: count, dtype: int64

In [ ]:
siloFourConfig = attack_data[attack_data[' Label'].isin(silos_config[4]['attacks'])]
siloFour = pd.concat([siloFourConfig, benign_silosFour], ignore_index=True)
print(siloFour[' Label'].value_counts())

 Label
BENIGN                      454264
Web Attack Brute Force        1507
Web Attack XSS                 652
Infiltration                    36
Web Attack SQL Injection        21
Name: count, dtype: int64

In [179]:
### Dealing with the class imbalance
def class_imbalance(dataframe, label):
    attack_samples = dataframe[dataframe[label] != 'BENIGN']
    benign_samples = dataframe[dataframe[label] == 'BENIGN']
    attack_count = len(attack_samples)

    benign_downsampled = benign_samples.sample(n = attack_count, random_state = RANDOM_SEED)

    balanced = pd.concat([benign_downsampled,attack_samples], ignore_index= True)

    return balanced

In [183]:
siloOne = class_imbalance(siloOne,' Label')
print(siloOne[' Label'].value_counts())
siloOne.to_csv('../silos_datasets/siloOne.csv')

 Label
BENIGN              251712
DoS Hulk            230124
DoS GoldenEye        10293
DoS slowloris         5796
DoS Slowhttptest      5499
Name: count, dtype: int64

In [185]:
siloTwo = class_imbalance(siloTwo,' Label')
print(siloTwo[' Label'].value_counts())
siloTwo.to_csv('../silos_datasets/siloTwo.csv')

 Label
BENIGN      288785
PortScan    158804
DDoS        128025
Bot           1956
Name: count, dtype: int64